language: node_js
node_js:
  - '6'
script: npm install && npm run build
after_success: npm run gh-pages-travis
env:
  global:
    - GIT_NAME="QuizMaster Bot"
    - SOURCE_DIR="./"
    - DEPLOY_BRANCH="master"
branches:
  except:
    - gh-pages