language: node_js
node_js:
  - '6'
script: npm install && npm run build
after_success: npm run gh-pages-travis
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="QuizMaster Bot"
    - SOURCE_DIR="./"
    - DEPLOY_BRANCH="master"
branches:
  except:
    - gh-pages
before_install:
  - openssl aes-256-cbc -K $encrypted_16982516dada_key -iv $encrypted_16982516dada_iv -in id_rsa.enc -out id_rsa -d